- name : copy xml file
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/test.xml


- name: Create jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file'), '/tmp/test.xml'}}"
    name: "{{item.job_name}}"
    user: admin
    password: admin123
    url: http://172.31.5.242:8080